/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PublishToWordPressPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  backend: "wordpress",
  wpSiteUrl: "",
  wpUsername: "",
  wpAppPassword: "",
  webhookDraftUrl: "",
  webhookQueueUrl: "",
  postFinalMarker: "**Post final :**"
};
function mimeForExtension(ext) {
  switch (ext.toLowerCase()) {
    case "png":
      return "image/png";
    case "jpg":
    case "jpeg":
      return "image/jpeg";
    case "webp":
      return "image/webp";
    case "gif":
      return "image/gif";
    default:
      return "application/octet-stream";
  }
}
var PublishToWordPressPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("upload", "Publish to WordPress", (evt) => {
      const menu = new import_obsidian.Menu();
      menu.addItem(
        (item) => item.setTitle("Draft to WordPress").setIcon("file-text").onClick(() => this.publishDraft())
      );
      if (this.settings.backend === "webhook") {
        menu.addItem(
          (item) => item.setTitle("Queue to targets (cibles)").setIcon("calendar").onClick(() => this.queueTargets())
        );
      }
      menu.showAtMouseEvent(evt);
    });
    this.addCommand({
      id: "publish-draft",
      name: "Publish current note as draft",
      callback: () => this.publishDraft()
    });
    this.addCommand({
      id: "queue-targets",
      name: "Queue current note to targets (webhook)",
      callback: () => this.queueTargets()
    });
    this.addSettingTab(new PublishSettingTab(this.app, this));
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async parseActiveNote() {
    var _a, _b;
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian.Notice("No active note.");
      return null;
    }
    const raw = await this.app.vault.read(file);
    const fm = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) != null ? _b : {};
    const marker = this.settings.postFinalMarker;
    const idx = raw.indexOf(marker);
    if (idx === -1) {
      new import_obsidian.Notice(`Marker not found in note: ${marker}`);
      return null;
    }
    const post = raw.slice(idx + marker.length);
    const lines = post.split("\n").filter((l) => !l.trim().startsWith("### Bloc"));
    const bodyTxt = lines.join("\n").trim().replace(/\*\(([^*]*)\)\*/g, "<em>($1)</em>").replace(/&/g, "&amp;");
    const paras = bodyTxt.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
    const html = paras.map((p) => "<p>" + p.replace(/\n/g, "<br>\n") + "</p>").join("\n");
    const title = fm.wp_title || file.basename.replace(/^Sujet — /, "");
    let cibles = [];
    if (fm.cibles) {
      cibles = Array.isArray(fm.cibles) ? fm.cibles.map(String) : [String(fm.cibles)];
    }
    let imageName = fm.image ? String(fm.image).replace(/^\[\[|\]\]$/g, "") : null;
    if (!imageName) {
      const m = raw.match(/!\[\[([^\]]+\.(?:png|jpe?g|webp|gif))\]\]/i);
      if (m)
        imageName = m[1];
    }
    let imageFile = null;
    if (imageName) {
      imageFile = this.app.metadataCache.getFirstLinkpathDest(imageName, file.path);
    }
    return { title, html, cibles, imageFile };
  }
  async publishDraft() {
    const note = await this.parseActiveNote();
    if (!note)
      return;
    if (this.settings.backend === "wordpress") {
      await this.publishToWordPress(note);
    } else {
      await this.publishViaWebhook(note);
    }
  }
  async publishToWordPress(note) {
    var _a, _b;
    const { wpSiteUrl, wpUsername, wpAppPassword } = this.settings;
    if (!wpSiteUrl || !wpUsername || !wpAppPassword) {
      new import_obsidian.Notice(
        "Configure WordPress site URL, username and application password in settings."
      );
      return;
    }
    const base = wpSiteUrl.replace(/\/+$/, "");
    const auth = "Basic " + btoa(`${wpUsername}:${wpAppPassword}`);
    new import_obsidian.Notice("Publishing draft to WordPress\u2026");
    try {
      let featuredMedia;
      if (note.imageFile) {
        const bin = await this.app.vault.readBinary(note.imageFile);
        const mediaRes = await (0, import_obsidian.requestUrl)({
          url: `${base}/wp-json/wp/v2/media`,
          method: "POST",
          headers: {
            Authorization: auth,
            "Content-Type": mimeForExtension(note.imageFile.extension),
            "Content-Disposition": `attachment; filename="${note.imageFile.name}"`
          },
          body: bin
        });
        featuredMedia = (_a = mediaRes.json) == null ? void 0 : _a.id;
      }
      const body = {
        title: note.title,
        content: note.html,
        status: "draft"
      };
      if (featuredMedia)
        body.featured_media = featuredMedia;
      const res = await (0, import_obsidian.requestUrl)({
        url: `${base}/wp-json/wp/v2/posts`,
        method: "POST",
        headers: { Authorization: auth, "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
      const created = res.json;
      new import_obsidian.Notice(`\u2705 Draft created (id ${(_b = created == null ? void 0 : created.id) != null ? _b : "?"}).`);
    } catch (e) {
      new import_obsidian.Notice("\u26D4 " + (e instanceof Error ? e.message : String(e)));
    }
  }
  async publishViaWebhook(note) {
    var _a;
    const url = this.settings.webhookDraftUrl;
    if (!url) {
      new import_obsidian.Notice("Configure the draft webhook URL in settings.");
      return;
    }
    new import_obsidian.Notice("Posting draft to webhook\u2026");
    try {
      const payload = await this.withImage(
        { title: note.title, content: note.html, status: "draft" },
        note
      );
      const res = await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });
      const sent = res.json;
      new import_obsidian.Notice(`\u2705 Sent (id ${(_a = sent == null ? void 0 : sent.id) != null ? _a : "?"}).`);
    } catch (e) {
      new import_obsidian.Notice("\u26D4 " + (e instanceof Error ? e.message : String(e)));
    }
  }
  async queueTargets() {
    if (this.settings.backend !== "webhook") {
      new import_obsidian.Notice("Queue is only available in webhook mode.");
      return;
    }
    const note = await this.parseActiveNote();
    if (!note)
      return;
    if (!note.cibles.length) {
      new import_obsidian.Notice("No 'cibles' in frontmatter.");
      return;
    }
    const url = this.settings.webhookQueueUrl;
    if (!url) {
      new import_obsidian.Notice("Configure the queue webhook URL in settings.");
      return;
    }
    new import_obsidian.Notice("Queuing\u2026");
    try {
      const payload = await this.withImage(
        { targets: note.cibles, wp_title: note.title, wp_content: note.html },
        note
      );
      await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });
      new import_obsidian.Notice(`\u2705 Queued (${note.cibles.join(", ")}).`);
    } catch (e) {
      new import_obsidian.Notice("\u26D4 " + (e instanceof Error ? e.message : String(e)));
    }
  }
  async withImage(payload, note) {
    if (note.imageFile) {
      const bin = await this.app.vault.readBinary(note.imageFile);
      payload.image_b64 = (0, import_obsidian.arrayBufferToBase64)(bin);
      payload.image_name = note.imageFile.name;
      payload.image_mime = mimeForExtension(note.imageFile.extension);
    }
    return payload;
  }
};
var PublishSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Backend").setDesc("How notes are published.").addDropdown(
      (d) => d.addOption("wordpress", "WordPress (direct REST)").addOption("webhook", "Custom webhook (n8n\u2026)").setValue(this.plugin.settings.backend).onChange(async (v) => {
        this.plugin.settings.backend = v;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.backend === "wordpress") {
      new import_obsidian.Setting(containerEl).setName("WordPress site URL").setDesc("e.g. https://example.com").addText(
        (t) => t.setValue(this.plugin.settings.wpSiteUrl).onChange(async (v) => {
          this.plugin.settings.wpSiteUrl = v.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("Username").addText(
        (t) => t.setValue(this.plugin.settings.wpUsername).onChange(async (v) => {
          this.plugin.settings.wpUsername = v.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("Application password").setDesc("WordPress \u2192 Users \u2192 Profile \u2192 Application Passwords.").addText((t) => {
        t.setValue(this.plugin.settings.wpAppPassword).onChange(async (v) => {
          this.plugin.settings.wpAppPassword = v.trim();
          await this.plugin.saveSettings();
        });
        t.inputEl.type = "password";
      });
    } else {
      new import_obsidian.Setting(containerEl).setName("Draft webhook URL").addText(
        (t) => t.setValue(this.plugin.settings.webhookDraftUrl).onChange(async (v) => {
          this.plugin.settings.webhookDraftUrl = v.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("Queue webhook URL").addText(
        (t) => t.setValue(this.plugin.settings.webhookQueueUrl).onChange(async (v) => {
          this.plugin.settings.webhookQueueUrl = v.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("\xAB Post final \xBB marker").setDesc("The note body is read after this text.").addText(
      (t) => t.setValue(this.plugin.settings.postFinalMarker).onChange(async (v) => {
        this.plugin.settings.postFinalMarker = v;
        await this.plugin.saveSettings();
      })
    );
  }
};

/* nosourcemap */